/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class StartUI extends Scene {
		public lbStart:Laya.Label;
		public lbEnd:Laya.Label;
		public lbTips:Laya.Label;
		public btnSetObs:Laya.Button;
		public btnFind:Laya.Button;
		public btnStart:Laya.Button;
		public btnEnd:Laya.Button;
		public btnChoose:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Start");
        }
    }
    REG("ui.StartUI",StartUI);
}